### PR TITLE
Update to 0.9.2

### PR DESCRIPTION
**Pull request by davisdude**

### CODE REVIEW

**Comment by davisdude** [comment]
Nevermind... ignore this.
But it doesn't work with 0.9.2

**Comment by a327ex** [comment]
The if check exists because in <0.9.2 that function isn't defined. It should work in 0.9.2, doesn't it?

**Comment by davisdude** [comment]
No, it throws an error:

```
Error

Utilities/thomas/input.lua: 6: bad argument #1 to 'loadGamepadMappings' (filename, File, or FileData expected)
```

**Comment by a327ex** [comment]
You need to place gamecontrollerdb.txt on the same folder you place the Input.lua file.

**Comment by davisdude** [comment]
It is. You can see it [here](https://github.com/davisdude/New-Base)

*edit: Fixed link

**Comment by a327ex** [comment]
The way you're doing your requires (using . instead of /) messes up what I'm expecting inside the Input file (print input_path to see). Just set gamecontrollerdb's path manually I guess.

**Pull request closed without merging**
